### PR TITLE
feat: partial fr translation review

### PR DESCRIPTION
**Pull request by dtourde**
Hello,

Thank you for your work !

There is a few fix and additions on the French translation, I'll try to help again later of other parts of the JSON.

### CODE REVIEW

**Comment by Clon1998** [comment]
Hey, I just changed the base branch to dev, as that branch already contained an updated French translation.

Could you verify my base-branch change and ensure that the translation is consistent?
Also, the dev branch includes some new language keys.

**Comment by Clon1998** [comment]
@dtourde, please have a look at the changes and conflicts.
I want to include the updated french translation in the next update, which I want to build during the upcoming week.

**Comment by dtourde** [comment]
I try to do it this evening

**Comment by dtourde** [comment]
@Clon1998 thanks for your patience, it should be ok now

**Pull request merged**
