### PR TITLE
Hungarian Language Update

### PR DESCRIPTION
**Pull request by AntoszHUN**
I updated the Hungarian language package.

Signed-off-by: AntoszHUN <zsikaiantal@gmail.com>

### CODE REVIEW

**Comment by Clon1998** [comment]
Oh my mistake, I think you forked it from master.
However, most of the new translation_key are in the dev branche.

**Comment by AntoszHUN** [comment]
> 

Okay.

**Comment by Clon1998** [comment]
> I reviewed and corrected the deficiency. The 2 files are identical.

They are not?
Comparing the first 20 lines of the [en.json](https://github.com/Clon1998/mobileraker/blob/dev/assets/translations/en.json) in the dev branch with your [hu.json](https://github.com/Clon1998/mobileraker/blob/c1325d7ed8157562437730ab88bc16688ee3d7f8/assets/translations/hu.json) from the merge request shows clearly that keys are missing.


image

**Comment by AntoszHUN** [comment]
> 



> > I reviewed and corrected the deficiency. The 2 files are identical.
> 
> They are not? Comparing the first 20 lines of the [en.json](https://github.com/Clon1998/mobileraker/blob/dev/assets/translations/en.json) in the dev branch with your [hu.json](https://github.com/Clon1998/mobileraker/blob/c1325d7ed8157562437730ab88bc16688ee3d7f8/assets/translations/hu.json) from the merge request shows clearly that keys are missing.
> 
> image

I do not understand. I downloaded it and it's exactly the same for me. But then something got mixed up. I'll check later. I'm working a lot now.

**Comment by Clon1998** [comment]
> > 
> 
> > > I reviewed and corrected the deficiency. The 2 files are identical.
> > 
> > 
> > They are not? Comparing the first 20 lines of the [en.json](https://github.com/Clon1998/mobileraker/blob/dev/assets/translations/en.json) in the dev branch with your [hu.json](https://github.com/Clon1998/mobileraker/blob/c1325d7ed8157562437730ab88bc16688ee3d7f8/assets/translations/hu.json) from the merge request shows clearly that keys are missing.
> > image
> 
> I do not understand. I downloaded it and it's exactly the same for me. But then something got mixed up. I'll check later. I'm working a lot now.

No worries!
Ive just picked the en.json file into your PR(2b9dd9b). Just update your repo and compare the en.json with the hu.json in the repository.

**Comment by Clon1998** [comment]
You can just base the translation from dev instead of master.
But no worries do like you normally would :)

**Comment by AntoszHUN** [comment]
> You can just base the translation from dev instead of master.
> But no worries do like you normally would :)

Okay. I solve it. I start from the already updated language. The change you sent is not currently there. My file exactly matches the contents of the en.json file available now in the Master branch. New en.json not merged. that's why I couldn't update it. Here is the error. As soon as the final en.json file is added to the Master branch, I will also update the hu.json file.

**Pull request closed without merging**
